title: Nexum Strategic Archive
description: A Collaborative Strategic Intelligence Node
baseurl: "/nexum-strategic-archive"
url: "https://nerdyar.github.io"
author: Mario Luis LÃ³pez
markdown: kramdown
theme: null
